theme: just-the-docs
url: "https://aider.chat"

lang: en
languages: ["en", "zh-CN"]
default_lang: en

collections:
  docs:
    output: true
    permalink: /:lang/:path/

# Analytics configuration
analytics:
  enabled: false  # Single switch to control analytics and cookie consent
  posthog_key: 'phc_99T7muzafUMMZX15H8XePbMSreEUzahHbtWjy3l5Qbv'
  posthog_host: 'https://us.i.posthog.com'

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: "README.md"
      type: "pages"
    values:
      description: "aider is AI pair programming in your terminal"

exclude:
  - "tmp*"
  - "**/tmp*"
  - OLD
  - "**/OLD/**"
  - "OLD/**"
  - vendor
  - feed.xml

aux_links:
  "GitHub":
    - "https://github.com/Aider-AI/aider"
  "Discord":
    - "https://discord.gg/Tv2uQnR88V"
  "Blog":
    - "/blog/"

nav_external_links:
  - title: "GitHub"
    url: "https://github.com/Aider-AI/aider"
  - title: "Discord"
    url: "https://discord.gg/Tv2uQnR88V"
  - title: "English"
    url: /en/
  - title: "中文"
    url: /zh-CN/

repository: Aider-AI/aider

callouts:
  tip:
    title: Tip
    color: green
  note:
    title: Note
    color: yellow
    
