source 'https://rubygems.org'
gem 'jekyll'
gem "just-the-docs", "0.8.2"
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem "webrick"
gem 'github-pages', group: :jekyll_plugins
gem "html-proofer"
gem "jekyll-multiple-languages-plugin", "~> 1.7.0"
gem "i18n", "~> 1.14"          # 国际化的依赖库